apiVersion: apps/v1
kind: Deployment
metadata:
  name: picket-front-deployment-v${BUILD_NUMBER}
  labels:
    app: picket-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picket-front
      version: v${BUILD_NUMBER}
  template:
    metadata:
      name: picket
      labels:
        app: picket-front
        version: v${BUILD_NUMBER}
    spec:
      containers:
        - name: front
          image: sagnwoo/picket-front:v${BUILD_NUMBER}
